baseURL = "https://securityforge.ca"
title = "Security Forge"
theme = "hugo-notepadium"
copyright = ""

languageCode = "en"  # for the RSS generation
defaultContentLanguage = "en"

hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "dark"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Jan 02, 2006"  # if unset, default is "2006-01-02"
readingTime = true  # show reading time after article date
logo = "/img/anvil3.png"
slogan = "Technical ramblings of an infosec professional"
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."

[params.assets]
css = ["css/fonts.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.share]
enable = false  # En/Disable share globally, default: false. You can always enable share on per page.
addThisId = ""
inlineToolId = ""

[params.math]
enable = false # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "github"
darkTheme = "dracula"

[params.profile]
  enable = true
  avatar = "/img/avatar.png"
  name = "Security Forge"
  bio = "Another blog containing the technical ramblings of an infosec professional"  # support markdown syntax
  twitter = "securityforge1"  # https://twitter.com/XXX
  github = "security-forge"  # https://github.com/XXX

[params.nav]
showCategories = false       # /categories/
showTags = true             # /tags/

[[params.nav.custom]]
title = "About"
url = "/about/"